# Settings for dream vortex application
# 
# General display settings

x-offset: 0.   # for horizontal -5
y-offset: 0.
z-offset: -4.  # for horizontal: 0
scale: 0.15

select-distance: 2

# General vortex settings
# 

a:
   min: 0.9
   max: 1.0
b:
   min: 0.3
   max: 0.7

delta-theta: 0.1     #originally 0.1
delta-z: 0.2         #originally 0.2

# vortex-particles settings
#

particle-step-size:
   min: 0.05
   max: 0.1

particle-velocity:
   min: 0.5
   max: 0.85

particle-radius:
   min: 1.0
   max: 3.0

particle-color-range:
   min: 0.3
   max: 0.8
   
particle-red-range:
   min: 0.3
   max: 0.8

particle-blue-range:
   min: 0.3
   max: 0.8

particle-green-range:
   min: 0.
   max: 0.3

particle-transparency: 0.3 # 0.3 good for vortex

# vortex-strip-static
#

use-color: true

static-count: 300

height:
   min: 0.25
   max: 1.0
   
# vortex-lines settings
#

count: 12

